[project]
name = "combined-encodings"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "clingcon>=5.2.1.post2",
    "clingo>=5.8.0",
    "flingo>=1.0.0",
    "networkx>=3.0",
    "openpyxl>=3.1",
    "matplotlib>=3.8",
]
